server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:AFatMan/SpringCloud-ConfigServer.git #GitHub上面的git仓库名字
          uri: https://github.com/AFatMan/SpringCloud-ConfigServer.git #http方式
          username: AFatMan #http方式需要账号密码,ssh方式不需要
          password: Liu361361.
          skip-ssl-validation: true #跳过ssl验证
          ####搜索目录
          search-paths:
            - SpringCloud-ConfigServer
        ####读取分支
        default-label: main
#      label: main
  #rabbitmq相关配置 15672是Web管理界面的端口；5672是MQ访问的端口
  rabbitmq:
    password: guest
    username: guest
    host: localhost
    port: 5672
#服务注册到eureka地址
eureka:
  client:
    service-url:
      #      defaultZone: http://localhost:7001/eureka # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版

##rabbitmq相关配置,暴露bus刷新配置的端点  调用命令刷新配置:curl -X POST "http://localhost:3344/actuator/bus-refresh"
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'