server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  type-aliases-package: com.mystudy.payment.entity

