server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      # 路由注册方式一:
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名

#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址 lb:负载平衡,动态路由
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由  即原先请求路径为:http://localhost:8001/payment/get/1,更改为 http://localhost:9527/payment/get/1,(保护真实端口)
        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址 lb:负载平衡,动态路由
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
            # 这个时间后才能起效
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
            # 两个时间点之间
            - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]
            # 带cookie的
            - Cookie=chocolate, ch.p
            # 带指定请求头的参数的CURL命令,更多类型参考com.mystudy.gateway.CloudGateway9527文档注释
            - Header=X-Request-Id, \d+Header=X-Request-Id, \d+
            - Host=**.mystudy.com # 主机地址
            - Method=GET # 请求方法
            - Query=username,\d+ #参数username的值必须为整数
            # 总结:Predicate就是为了实现一组匹配规则，让请求过来找到对应的Route进行处理。


eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
#      defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka